name: permimp
channels:
    - conda-forge
dependencies:
    - python==3.7
    - numpy==1.16.4
    - pandas==0.24.2
    - scipy==1.3.0
    - scikit-learn==0.21.2
    - eli5==0.8.2
    - jupyter==1.0.0
    - matplotlib==3.1.0
